### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by byxox** [JustasMasiulis/lazy_importer#16]
Hello

I'm using Windows 10.
Visual Studio 2017 Ent. I'm using x64
When compiling the project:
http://prntscr.com/ltdurm
I'm getting the error and what may be missing.

**Comment by JustasMasiulis** [comment]
Could you provide the code that causes this? Also the error information from the output window instead of errors window is a bit more reliable so it would be great if you could add that.

As for me it would seem that I have no problems compiling this:
```cpp
// ofc this code makes you crash but that's beside the point
    LI_FN(OutputDebugStringA).in_cached(LI_MODULE("ntdll.dll").get())("hello world");
    LI_FN(OutputDebugStringA)("hello world");
    LI_FN(VirtualProtect).in_cached(LI_MODULE("kernel32.dll").cached());
    LI_FN(VirtualProtect).nt_cached();
````

**Comment by JustasMasiulis** [comment]
Will fix this soon - was compiling with clang which did not seem to have any problems

**Comment by JustasMasiulis** [comment]
Should have been fixed by the last commit.
If the issue persists reopen it with the new errors you are experiencing.
