### ISSUE TITLE
Question - d3d9 ?

### ISSUE THREAD

**Issue by LeimonDust** [JustasMasiulis/lazy_importer#18]
Hello
How i can use this library for hide CreateDevice?

`if (pD3D->CreateDevice(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, hwnd, D3DCREATE_HARDWARE_VERTEXPROCESSING, &g_d3dpp, &g_pd3dDevice) < 0)
	{
                pD3D->Release();
		return 0;
	}`

**Comment by JustasMasiulis** [comment]
AFAIK there is nothing to import/hide here. In the binary this will simply be invoking a function pointer that lies in the vtable.

**Comment by LeimonDust** [comment]
Oh, sorry
I wanted to ask how to hide this import:
`pD3D = Direct3DCreate9(D3D_SDK_VERSION);
if (pD3D == NULL)
return 0;`

This seems not working for me
`pD3D = LI_FN(Direct3DCreate9)(D3D_SDK_VERSION);`

**Comment by JustasMasiulis** [comment]
That should be completely fine. Could it be that you forgot to load d3d9.dll? Because if you have no imports from it, it won't be automatically loaded on startup.

**Comment by JustasMasiulis** [comment]
More than a week has passed so I'll consider this issue resolved
