### ISSUE TITLE
This lib help me?

### ISSUE THREAD

**Issue by lurumdare** [JustasMasiulis/lazy_importer#19]
about WSASend/WSARecv winsock function.

**Comment by JustasMasiulis** [comment]
Yes?

**Comment by jaspergould** [comment]
@JustasMasiulis she can protect WSASend/WSARecv?

**Comment by SekkaiDev** [comment]
I have an issue using it in recv

` LI_FN(recv).in(LI_MODULE("ws2_32.dll").get())(this->_sktConnectSocket, buffer, len, flags);`

**Comment by JustasMasiulis** [comment]
What would the issue be? For me it would seem to be working just fine
![test](https://user-images.githubusercontent.com/16763439/55744147-e0f1ee80-5a3c-11e9-823b-0c568e041c6d.png)

**Comment by SekkaiDev** [comment]
[https://imgur.com/a/IEQh5Ne](url)

**Comment by JustasMasiulis** [comment]
Could you send me the `ws2_32.dll` from your machine? Hopefully I'll be able to reproduce the problem and find the solution.

Alternatively you can try out the `safe` function variants:
`LI_MODULE("ws2_32.dll").safe()`
and
`LI_FN(recv).in_safe(....)(this->_sktConnectSocket, buffer, len, flags);`

These should reliably return `nullptr` on failure

**Comment by SekkaiDev** [comment]
Yes, im using 32bit version, i tried to use safe etc doenst work, i tried alot to resolve it myself, but is very strange behavior

[ws2_32.zip](https://github.com/JustasMasiulis/lazy_importer/files/3055922/ws2_32.zip)

**Comment by JustasMasiulis** [comment]
Seems like I cannot reproduce it.

A possible fix could be simply using a function that does lookup in all modules. If you are concerned with performance I'd recommend using `cached` functions or just defining macro to do it by default. For example this should work: `LI_FN(recv)(this->_sktConnectSocket, buffer, len, flags);`

As you don't crash the problem must be the fact that it cannot find the module. I have no idea what would the reason for that be. If you want to debug further you can try putting a breakpoint in `lazy_module::get` and see if you can spot your own module by looking at the value of `BaseDllName`.

**Comment by SekkaiDev** [comment]
@JustasMasiulis Thanks for you for the try, and congrats, its a really nice lib...

To finish here i want todo a question, you already tested if its ok to use alot this lib inside class members?
here this issue happens only in class members
