### ISSUE TITLE
Nice suggestion?

### ISSUE THREAD

**Issue by jaspergould** [JustasMasiulis/lazy_importer#20]
![lovvve](https://user-images.githubusercontent.com/8020186/56021604-8b566400-5d12-11e9-8e72-416ade41c556.png)

**Comment by jaspergould** [comment]
Reparse cpp file to lazy add obfuscation automatic.

**Comment by JustasMasiulis** [comment]
There is a multitude of problems with this approach.

- Do you really want every single function to be obfuscated.
- I'd need to somehow find out what functions are actually imported.
- Not all functions are equal and you probably would want a more fine grained control on how to obfuscate them
- When and by whom do the modules get loaded?

Lastly I don't think it's worth the effort of spending probably hundreds of hours just to simplify something that takes maybe a few seconds for each imported function call.
