### ISSUE TITLE
Macros support?

### ISSUE THREAD

**Issue by jaspergould** [JustasMasiulis/lazy_importer#21]
How to use this project with https://github.com/ITHare/obf ?

**Comment by JustasMasiulis** [comment]
The library simply returns a function pointer. If you want some sort of further obfuscation you can go ahead and apply it.
However against static analysis this library alone is fully enough to hide what you're calling and there is no point of applying further obfuscation on the function pointer.

**Comment by jaspergould** [comment]
@JustasMasiulis ok. and you can see the difference between obfuscation xorstr and obf literals? maybe obf lib better for literals

**Comment by JustasMasiulis** [comment]
I can't really comment on the obf library string encryption.

The thing with xorstr is that it is designed to be as fast as possible and the main thing that guards it from decompilers is the heavy use of SSE and AVX intrinsics.

Again. I'd argue that both libraries do perfectly well against static analysis. The second you attach a debugger or emulate the code you will see what's happening.

**Comment by jaspergould** [comment]
@JustasMasiulis already saw.

**Comment by JustasMasiulis** [comment]
I guess this question is answered, so I will close the issue now.

**Comment by jaspergould** [comment]
@JustasMasiulis ok
