### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mq1n** [JustasMasiulis/lazy_importer#22]
I tried build with VS2019 and it's happens.

![image](https://user-images.githubusercontent.com/22681718/56469760-7d0cf400-6446-11e9-93a6-f3ca5f019305.png)

Code:
`
	LI_FN(CreateDirectoryA)("NoMercy", NULL);
`

Full log:
`2>CMake does not need to re-run because D:/Workspace/Anti/Current projects/NoMercyV2/_vsproj/Source/Client/PC/Windows/SDK/CXX/CMakeFiles/generate.stamp is up-to-date.
2>main.cpp
2>Utils.cpp
2>D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(496): error C2664: 'BOOL (LPCSTR,LPSECURITY_ATTRIBUTES)': cannot convert argument 2 from '_Ty' to 'LPSECURITY_ATTRIBUTES'
2>        with
2>        [
2>            _Ty=int
2>        ] (compiling source file D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp)
2>D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(494): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast (compiling source file D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp)
2>D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp(28): note: see reference to function template instantiation 'decltype(auto) li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()<char*,int>(char *&&,int &&) const' being compiled
2>D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(494): error C3169: 'decltype(auto)': cannot deduce type for 'auto' from 'BOOL' (compiling source file D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp)
2>D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp(28): error C3779: 'li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()': a function that returns 'decltype(auto)' cannot be used before it is defined
2>D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(493): note: see declaration of 'li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()'
2>Done building project "NoMercy_CXX_SDK_x64.vcxproj" -- FAILED.
`

**Comment by JustasMasiulis** [comment]
Could you show compiler output windows instead? The Visual Studio errors window is not reliable.

**Comment by mq1n** [comment]
Sure,

`
  main.cpp
D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(496): error C2664: 'BOOL (LPCSTR,LPSECURITY_ATTRIBUTES)': cannot convert argument 2 from '_Ty' to 'LPSECURITY_ATTRIBUTES'
          with
          [
              _Ty=int
          ]
  D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(494): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
  D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp(28): note: see reference to function template instantiation 'decltype(auto) li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()<char*,int>(char *&&,int &&) const' being compiled
D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(494): error C3169: 'decltype(auto)': cannot deduce type for 'auto' from 'BOOL'
D:\Workspace\Anti\Current projects\NoMercyV2\Source\Client\PC\Windows\SDK\CXX\src\main.cpp(28): error C3779: 'li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()': a function that returns 'decltype(auto)' cannot be used before it is defined
  D:\Workspace\Anti\Current projects\NoMercyV2\Extern\include\lazy_importer.hpp(493): note: see declaration of 'li::detail::lazy_function<2965998675,BOOL (__cdecl *)(LPCSTR,LPSECURITY_ATTRIBUTES)>::operator ()'
`

**Comment by JustasMasiulis** [comment]
Ah. Don't use NULL. Use nullptr and it should work.
