### ISSUE TITLE
Question how to test .safe()

### ISSUE THREAD

**Issue by Mecanik** [JustasMasiulis/lazy_importer#24]
So you have introduced the .safe() method which returns 0 on failed operation, however how could I test this ? I tried different ways, but for example if I rename module I get an exception, if I rename to fake function it will say undefined and so on.

I need to test this for failure and see if it returns 0 upon failure, however I see "static void" template so I cannot understand how it returns 0 ?

Can you please give me an example ?

**Comment by JustasMasiulis** [comment]
Fixed
