### ISSUE TITLE
LI and vm

### ISSUE THREAD

**Issue by lurumdare** [JustasMasiulis/lazy_importer#25]
LI needed for VM protection?
With force inline +10-15 sec for execution vm.

Tested on VMProtect.

**Comment by Mecanik** [comment]
Don't virtualize the parts where you use LI.

**Comment by JustasMasiulis** [comment]
You shouldn't use lazy importer in virtualized code. There is no point in doing that as virtualization is a much stronger obfuscation method compared to lazy importer.
