### ISSUE TITLE
not working with DefWindowProcA

### ISSUE THREAD

**Issue by beranos** [JustasMasiulis/lazy_importer#27]
hi i'm trying to use with DefWindowProcA but i crash 
this is the code:
`LI_FN( LoadLibraryA )( "User32.dll" );
return LI_FN( DefWindowProcA ).in( LI_MODULE( "User32.dll" ).get( ) )( window, message, wparam, lparam );`

**Comment by JustasMasiulis** [comment]
* Check whether module lookup fails or function lookup fails. Safe function variants will return null instead of crashing.
* If it's the module lookup try enabling case insensitive lookup macro
* If it's function lookup try enabling forwarded export lookup

**Comment by beranos** [comment]
im crashing because base is nullptr: https://i.imgur.com/TeEwmZc.png
callstack: https://i.imgur.com/gC3xYYl.png

tried 
#define LAZY_IMPORTER_CASE_INSENSITIVE
#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS

but still the same

**Comment by beranos** [comment]
no i don't have any anti debugging, i'm on the latest windows version (1909, 18363.752) 
i'm using the default compiler visual studio offers 
also with your code it doesn't crash anymore but code after auto fn doesn't get executed it's like stucked there

**Comment by JustasMasiulis** [comment]
Stuck may be because it's not finding anything and is looping over. Considering the fact thatt the first call randomnly started working are you sure there isn't some undefined behaviour like a missing return statement etc

**Comment by beranos** [comment]
> Stuck may be because it's not finding anything and is looping over. Considering the fact thatt the first call randomnly started working are you sure there isn't some undefined behaviour like a missing return statement etc

no, i put your code at the start of my main function before i call anything

**Comment by JustasMasiulis** [comment]
try this code
```cpp
    auto mod = LI_FN(LoadLibraryA)("User32.dll");
    auto fn  = LI_FN(DefWindowProcA).in(mod);```

**Comment by beranos** [comment]
> ```c++
>  auto mod = LI_FN(LoadLibraryA)("User32.dll");
>     auto fn  = LI_FN(DefWindowProcA).in(mod);
> ```

yes this is working fine and it's not getting stuck anymore

**Comment by JustasMasiulis** [comment]
That's very strange. User32.dll lookup fails somehow.

**Comment by beranos** [comment]
that doesn't get stuck but when trying it on the original code i have i crash at the same location as before (base is nullptr)

**Comment by JustasMasiulis** [comment]
so in the loadlibrary or DefWindowProcA lookup? Because stack trace you sent earlier shows the loadlibrary missing IIRC

**Comment by beranos** [comment]
> so in the loadlibrary or DefWindowProcA lookup? Because stack trace you sent earlier shows the loadlibrary missing IIRC

just DefWindowProcA, i use loadlibrary with lazyimporter in the same project so yeah

**Comment by JustasMasiulis** [comment]
`const auto mod = LoadLibraryA( "User32.dll" ); return LI_FN( DefWindowProcA ).in( mod )( window, message, wparam, lparam );` does not use operator() at all so I'm not sure what kind of stack trace you are showing me here

**Comment by JustasMasiulis** [comment]
If you just omitted LI_FN for the loadlibrary part it has to be the LoadLibrary that is somehow not getting found

**Comment by JustasMasiulis** [comment]
Could possibly be a race cond if you are spamming loadlib but I doubt it would be this consistent

**Comment by beranos** [comment]
if i just use 
`const auto mod = LoadLibraryA( "User32.dll" );
	printf( "%p \n", mod );`
nothing crashes but as soon i use lazy importer for DefWindowProcA i crash

**Comment by JustasMasiulis** [comment]
this makes no sense whatsoever. LoadLib alone works fine but then crashes if you add another line.

**Comment by beranos** [comment]
yeah idk, i'll just not protect that import it's not a problem thanks for trying to help anyways

**Comment by beranos** [comment]
https://i.imgur.com/eDlFumB.png
"Buffer" changes everytime if i press continue for example once it was kernel32.dll, user32.dll etc

**Comment by JustasMasiulis** [comment]
with case insensitive it should work just fine then

**Comment by beranos** [comment]
enabled with #define LAZY_IMPORTER_CASE_INSENSITIVE
still never calls   return (T)(e.value->DllBase);

**Comment by JustasMasiulis** [comment]
how exactly are you enabling case insensitive mode. Because I feel like you only enable it in 1 file and not globally trough compiler flags or by editing the lazy importer file itself.

**Comment by beranos** [comment]
> how exactly are you enabling case insensitive mode. Because I feel like you only enable it in 1 file and not globally trough compiler flags or by editing the lazy importer file itself.

i just changed from
#ifdef LAZY_IMPORTER_CASE_INSENSITIVE
#define LAZY_IMPORTER_TOLOWER(c) (c >= 'A' && c <= 'Z' ? (c | (1 << 5)) : c)
#else
#define LAZY_IMPORTER_TOLOWER(c) (c)
#endif

to

#define LAZY_IMPORTER_TOLOWER(c) (c >= 'A' && c <= 'Z' ? (c | (1 << 5)) : c)

(#define didn't work so i just did this temporary)

**Comment by JustasMasiulis** [comment]
what about the breakpoint thing? Does it get hit the same way in real code? Can you change the string to match the one that you see in your own code?

**Comment by beranos** [comment]
> what about the breakpoint thing? Does it get hit the same way in real code? Can you change the string to match the one that you see in your own code?

yes now when i breakpoint  return (T)(e.value->DllBase); get's called fine and i don't get stuck anymore

**Comment by JustasMasiulis** [comment]
so... it works?

**Comment by beranos** [comment]
> so... it works? did you change anything?

test code it works, but when putting it into my wndproc function it crashes

**Comment by JustasMasiulis** [comment]
So did you try placing the breakpoint and checking out real code inside your wndproc function?

**Comment by JustasMasiulis** [comment]
I'll try creating a windows and testing it out in wndproc too

**Comment by JustasMasiulis** [comment]
Should have fixed it.
`LI_FN(DefWindowProcA).forwarded()(...)` should work now.

**Comment by beranos** [comment]
> Should have fixed it.
> `LI_FN(DefWindowProcA).forwarded()(...)` should work now.

still crashes for me :\

**Comment by JustasMasiulis** [comment]
so it works, issue closed?

**Comment by beranos** [comment]
> so it works, issue closed?

if i try doing LI_FN(DefWindowProcA).forwarded()(...) other imports i protect start crashing too, without that they don't crash

**Comment by JustasMasiulis** [comment]
what are those imports

**Comment by beranos** [comment]
> what are those imports

all of them, for example if i try to comment out LI_FN( GetWindowThreadProcessId )( .. ) then another one crashes in this case LI_FN( LoadCursorA )( .. );

**Comment by JustasMasiulis** [comment]
but.. only 1 code path changed and that is inside the forwarded hash function that only gets used for forwarded stuff

**Comment by beranos** [comment]
> but.. only 1 code path changed and that is inside the forwarded hash function that only gets used for forwarded stuff

idk, if i replace LI_FN(DefWindowProcA).forwarded( ) with DefWindowProcA then everything stops crashing, btw the crash is on the main function before that function that uses DefWindowProcA even gets called
