### ISSUE TITLE
LI_MODULE macro doesn't handle char* parameter

### ISSUE THREAD

**Issue by mq1n** [JustasMasiulis/lazy_importer#29]
Like the title said, "LI_MODULE" is doesn't not handle char* or const char* module name in MSVC.

https://godbolt.org/z/ZZbLJc

**Comment by JustasMasiulis** [comment]
this isn't really the intended way of usage of LI_MODULE. It expects a compile time string. Passing it a random pointer wont work.

**Comment by JustasMasiulis** [comment]
I will probably be making v3 of lazy importer with new API that allows this and gets rid of all the ugly member functions but that will be only in around a few months when I have some more spare time
