### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by SLIpros** [JustasMasiulis/lazy_importer#31]
```
#include <Windows.h>
#include "lazy_importer.hpp"

int main() {
	const auto shell32 = LI_MODULE("Shell32.dll").cached();
	const auto shellExecute = LI_FN(::ShellExecuteA).in(shell32);
	shellExecute(nullptr, "open", "explorer.exe", nullptr, nullptr, SW_SHOWNORMAL);

	return 0;
}
```

When i include Windows.h before lazy_importer then i have endless loop in "LI_MODULE" at
```
template<hash_t::value_type Hash>
struct lazy_module : lazy_base<lazy_module<Hash>> {
    template<class T = void*, class Enum = unsafe_module_enumerator>
    LAZY_IMPORTER_FORCEINLINE static T get() noexcept
    {
        Enum e;
        do { // here
            if (hash(e.value->BaseDllName) == Hash)
                return (T)(e.value->DllBase);
        } while (e.next());
        return {};
    }
};
```

if i include Windows.h after then it crash with "READ_ACCESS_MEMORY_EXCEPTION" in "LI_FN" at 
```
template<class CharT = char>
LAZY_IMPORTER_FORCEINLINE hash_t::value_type hash(const CharT* str) noexcept
{
    hash_t::value_type value = hash_t::offset;

    for (;;) {            	
        char c = *str++; // here
        if (!c)
            return value;
        value = hash_t::single(value, c);
    }
}
```

What i do wrong?
I am using last updated VS 2019 at Windows 10 2004

**Comment by hzqst** [comment]
make sure Shell32.dll is loaded before using LI_FN

**Comment by SLIpros** [comment]
> make sure Shell32.dll is loaded before using LI_FN

```
#define LAZY_IMPORTER_CASE_INSENSITIVE

#include <windows.h>
#include "lazy_importer.hpp"

int main()
{
	HINSTANCE hDllShell = ::LoadLibrary(L"Shell32.dll");
	
	const auto shell32 = LI_MODULE("Shell32.dll").cached();
	const auto shellExecute = LI_FN(::ShellExecuteA).in(shell32);
	shellExecute(nullptr, "open", "explorer.exe", nullptr, nullptr, SW_SHOWNORMAL);

	return 0;
}
```

This fixed first problem, but it's still crashes with "READ_ACCESS_MEMORY_EXCEPTION" in "LI_FN"

**Comment by hzqst** [comment]
> > make sure Shell32.dll is loaded before using LI_FN
> 
> ```
> #define LAZY_IMPORTER_CASE_INSENSITIVE
> 
> #include <windows.h>
> #include "lazy_importer.hpp"
> 
> int main()
> {
> 	HINSTANCE hDllShell = ::LoadLibrary(L"Shell32.dll");
> 	
> 	const auto shell32 = LI_MODULE("Shell32.dll").cached();
> 	const auto shellExecute = LI_FN(::ShellExecuteA).in(shell32);
> 	shellExecute(nullptr, "open", "explorer.exe", nullptr, nullptr, SW_SHOWNORMAL);
> 
> 	return 0;
> }
> ```
> 
> This fixed first problem, but it's still crashes with "READ_ACCESS_MEMORY_EXCEPTION" in "LI_FN"

"::ShellExecuteA" -> "ShellExecuteA"
