### ISSUE TITLE
Netapi32 Function Calls

### ISSUE THREAD

**Issue by hlldz** [JustasMasiulis/lazy_importer#32]
Hi,

First of all, thank you for such a project.

When I try to use the DsRoleGetPrimaryDomainInformation API in Netapi32.dll I constantly get an Access Violation error.

I've given below the working sample code:

```
DSROLE_PRIMARY_DOMAIN_INFO_BASIC* inf;
DWORD dw;

dw = DsRoleGetPrimaryDomainInformation(NULL, DsRolePrimaryDomainInfoBasic, (PBYTE*)&inf);

if (dw != ERROR_SUCCESS) {
    std::cout << "NO";
}
```

I've given below the LI code with which I got the error:

```
auto mod = LoadLibraryA("Netapi32.dll");
printf("%p \n", mod);

auto func = LI_FN(DsRoleGetPrimaryDomainInformation).in(LI_MODULE("Netapi32.dll").get());

DSROLE_PRIMARY_DOMAIN_INFO_BASIC* inf;
DWORD dw;

dw = func(NULL, DsRolePrimaryDomainInfoBasic, (PBYTE*)&inf); //Error line: Access Violation

if (dw != ERROR_SUCCESS) {
    std::cout << "NO";
}
```

Do you have any ideas for solving the problem?

**Comment by Mecanik** [comment]
First of all, try to use .in_safe and .safe() to see if the result is 0 or not. Then, check if the function is a forwarded function.

**Comment by JustasMasiulis** [comment]
My bet would be that it's a forwarded export (note that `.in` never resolves forwarded exports). You can either use one of the `*_forwarded` functions or enable the functionality globally with a macro.

**Comment by hlldz** [comment]
I tried the possible solutions but it is not worked.

**Comment by hlldz** [comment]
Btw, yes it is forwarded function from netapi32.dll to dsrole.dll. If I load dsrole.dll and call the API with LI get() and in() it is works. But when I use netapi32.dll and call forwarded() it is not works.

**Comment by JustasMasiulis** [comment]
Yeah that is one of the quirks of the api. Unlike GetProcAddress it doesn't load the dependencies if they are missing. I will be addressing this issue when I release the version 3 of API

**Comment by hlldz** [comment]
Thank you, I will wait next release.
