### ISSUE TITLE
Can't use OpenProcessToken

### ISSUE THREAD

**Issue by playday3008** [JustasMasiulis/lazy_importer#34]
![image](https://user-images.githubusercontent.com/18056374/99897713-e9d81800-2c93-11eb-93d2-3f6fd62c6c01.png)
![image](https://user-images.githubusercontent.com/18056374/99897717-f65c7080-2c93-11eb-8032-39d638093175.png)

with
#define LAZY_IMPORTER_CASE_INSENSITIVE
and
#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS
![image](https://user-images.githubusercontent.com/18056374/99897728-11c77b80-2c94-11eb-9d80-9494f30d2ede.png)

Windows 10 + VisualStudio 2019

**Comment by Mecanik** [comment]
`LI_FN(OpenProcessToken).in(LI_MODULE("Advapi32.dll").get())();`

**Comment by playday3008** [comment]
thx
