### ISSUE TITLE
LI_MODULE doesnt always return pointer.

### ISSUE THREAD

**Issue by roll-cage** [JustasMasiulis/lazy_importer#37]
Hey, can you try out the following project i created for this question: https://github.com/roll-cage/li_module_question
Please run it in Debug and x86.
Why can some dlls not be resolved by LI_MODULE but by GetModuleHandleA?
The output for me is the following:
77190000
00000000
77B80000
77B80000
7BAD0000
7BAD0000
7BA10000
00000000

**Comment by roll-cage** [comment]
The project only consists of this code:


#include &lt;windows.h&gt;
        #include &lt;iostream&gt;
      
      
        #include &lt;lazy_importer.hpp&gt;
      
      
        

      
      
        int main()
      
      
        {
      
      
        	std::cout &lt;&lt; GetModuleHandleA("kernel32.dll") &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; LI_MODULE("kernel32.dll").safe() &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; GetModuleHandleA("ntdll.dll") &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; LI_MODULE("ntdll.dll").safe() &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; GetModuleHandleA("ucrtbased.dll") &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; LI_MODULE("ucrtbased.dll").safe() &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; GetModuleHandleA("msvcp140d.dll") &lt;&lt; std::endl;
      
      
        	std::cout &lt;&lt; LI_MODULE("msvcp140d.dll").safe() &lt;&lt; std::endl;
      
      
        }

**Comment by JustasMasiulis** [comment]
Did you try defining `LAZY_IMPORTER_CASE_INSENSITIVE`?

**Comment by roll-cage** [comment]
Perfect, thank you vey much.
