### ISSUE TITLE
LI_MODULE_SAFE returns process base

### ISSUE THREAD

**Issue by adspro15** [JustasMasiulis/lazy_importer#4]
I use:
DWORD64 ntdllbase = (DWORD64)LI_MODULE_SAFE("ntdll.dll");
returns = 0;
what's wrong?

**Comment by Mecanik** [comment]
Why would you use DWORD64 ?? Why would you even use DWORD...

**Comment by Mecanik** [comment]
@JustasMasiulis No worries, I am just surprised... like everyday more and more.

**Comment by adspro15** [comment]
@JustasMasiulis Thanks for solving problem
But there was another problem)
Using LI_GET crashing program
my code:
DWORD64 NtCloseAdress = (DWORD64)LI_GET("ntdll.dll", "NtClose");

**Comment by JustasMasiulis** [comment]
Oh. Well I'd say that is a rather expected behaviour because first parameter of LI_GET is the module address and not its name.

**Comment by JustasMasiulis** [comment]
O.o  Is it reproducible? Could you try debugging a little bit and checking if there is possibly a hash collision between process name and the module name?

**Comment by JustasMasiulis** [comment]
Ugh... How can I be this blind... Fixed it...
