### ISSUE TITLE
console printing

### ISSUE THREAD

**Issue by Nulldi** [JustasMasiulis/lazy_importer#41]
Hi, idk what i am doing wrong but i tried to use printf with Lazy Importer but it crashes is there any other way to print into the console or am i doing something wrong? Thanks.

Exception thrown at 0x00007FF63F531554 in test.exe: 0xC0000005: Access violation reading location 0x000000000000003C.

code:
LI_FN(printf)("%s\n", "Hi Test!");

**Comment by JustasMasiulis** [comment]
That's likely because there is no dll that exports function named `printf`

with MSVC crt printf is a wrapper around `_stdio_common_vfprintf`

**Comment by Nulldi** [comment]
Thanks for helping. I am useing now wprintf which is exported by the kernelbase.dll.

LI_FN(wprintf)(L"%S \n", msg.c_str());
