### ISSUE TITLE
These function addresses get errors

### ISSUE THREAD

**Issue by icyfox168168** [JustasMasiulis/lazy_importer#43]
kernel32.dll WIN10

static const char* pass_func[] =
{
"CreateRemoteThreadEx",
"DeleteProcThreadAttributeList",
"GetCurrentThreadStackLimits",
"GetOverlappedResultEx",
"GetProcessDefaultCpuSets",
"GetProcessMitigationPolicy",
"GetSystemCpuSetInformation",
"GetThreadDescription",
"GetThreadSelectedCpuSets",
"InitializeProcThreadAttributeList",
"IsProcessCritical",
"OpenProcessToken",
"OpenThreadToken",
"QueryProtectedPolicy",
"SetProcessDefaultCpuSets",
"SetProcessDynamicEHContinuationTargets",
"SetProcessMitigationPolicy",
"SetProtectedPolicy",
"SetThreadDescription",
"SetThreadSelectedCpuSets",
"SetThreadToken",
"UpdateProcThreadAttribute",
NULL
};

**Comment by JustasMasiulis** [comment]
I don't do apiset resolution, so that kind of explains the failures
