### ISSUE TITLE
Exception when used with HeapAlloc

### ISSUE THREAD

**Issue by R3uan3** [JustasMasiulis/lazy_importer#48]
When i try `LI_FN` with `HeapAlloc` i get an exception:
```c++
    ULONG cbBuffer = 131072;
    PVOID pBuffer = NULL;
    NTSTATUS Status = STATUS_INFO_LENGTH_MISMATCH;
    HANDLE hHeap = LI_FN(GetProcessHeap)();
    tNTQSI fpQSI = (tNTQSI)GetProcAddress(LI_FN(GetModuleHandleA)("ntdll.dll"), "NtQuerySystemInformation");

    pBuffer = LI_FN(HeapAlloc)(hHeap, HEAP_ZERO_MEMORY, cbBuffer);
```

![image](https://user-images.githubusercontent.com/103058225/192686577-0e306655-9035-4f14-a8c1-b7f1b1b536a6.png)

Based on  https://github.com/JustasMasiulis/lazy_importer/issues/40
I tried this:
```c++
    auto Kernel32DLL = LoadLibrary(L"Kernel32.dll");
    //auto Kernel = GetProcAddress(GetModuleHandleA("kernel32.dll"), "HeapAlloc");
    pBuffer = LI_FN(HeapAlloc).in(LI_MODULE("Kernel32.dll").cached())(hHeap, HEAP_ZERO_MEMORY, cbBuffer);
```
But the program has frozen.

> cached indicates that the result is only computed during the first call and later reused.
> Non caching functions do not leave anything in data sections.

When should I use the cached version? 
When the API is called constantly in a short period of time?

**Comment by JustasMasiulis** [comment]
a) Do you have case insensitive comparison enabled? Lookup of kernel32 might fail if it's not enabled.
b) Do you have forwarded export resolution enabled?

> When should I use the cached version?
> When the API is called constantly in a short period of time?

Essentially yes. Cached versions only do lookup 1 time. Non-cached does lookup on every use.

Lastly I'd suggest using `RtlAllocateHeap` and `RtlFreeHeap` from ntdll. It's the same exact function.

**Comment by R3uan3** [comment]
I tried with both a) b) but it still 'frozen' after reading the `.cached()` line.
Compilable example:
```c++
#include "pch.h"
#include "lazy_importer.h"

#define LAZY_IMPORTER_CASE_INSENSITIVE
#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS

BOOL CALLBACK EnumParentFind(HWND hWnd, LPARAM lParam)
{
    HINSTANCE hUser = LoadLibrary(L"User32.dll");

    //if (IsWindowVisible(hWnd)
    if (LI_FN(IsWindowVisible).in(LI_MODULE("User32.dll").cached())(hWnd))
    {
       //...
    }
}

int _tmain(int argc, _TCHAR* argv[]) 
{    
    while (true)
    {
        LI_FN(EnumWindows)(EnumParentFind, NULL);
        Sleep(1000);
    }
    return 0;
}
```
In this case as `IsWindowVisible` is called often, with:
`if (LI_FN(IsWindowVisible)(hWnd)` it works but uses like 12% of CPU, compared to 0.5% without `LI_FN`
and with `.cached()` it 'frozen'

**Comment by R3uan3** [comment]
@JustasMasiulis you could reproduce it on your side?

**Comment by JustasMasiulis** [comment]
Code below works for me. Notably move the defines before lazy importer is included and load user32.dll before EnumWindows call.

```
#define LAZY_IMPORTER_CASE_INSENSITIVE
#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS

#include "li.hpp"

HINSTANCE hUser = LoadLibraryW(L"User32.dll");

BOOL CALLBACK EnumParentFind(HWND hWnd, LPARAM lParam)
{
    // if (IsWindowVisible(hWnd)
    if (LI_FN(IsWindowVisible)(hWnd)) {} // <- works
    if (LI_FN(IsWindowVisible).cached()(hWnd)) {} // <- works
    if (LI_FN(IsWindowVisible).in(hUser)(hWnd)) {} // <- works
    if (LI_FN(IsWindowVisible).in_cached(hUser)(hWnd)) {} // <- works
    if (LI_FN(IsWindowVisible).in(LI_MODULE("User32.dll").cached())(hWnd)) // <- works
    {
       //...
    }
   return true;
}

int main(int argc, char* argv[]) 
{    
    LI_FN(EnumWindows)(EnumParentFind, 0);
    Sleep(1000);
}```

There is some potential for this to be an issue with apisets because I don't resolve them, but 🤷
