### ISSUE TITLE
Not working in DLL?

### ISSUE THREAD

**Issue by 0Z0SK0** [JustasMasiulis/lazy_importer#49]
I use Lazy to hide imports in my dll (which I inject into other process), but not a single line of code is executed after calling LI_FN.
![image](https://user-images.githubusercontent.com/45397007/213863947-5d0869f7-1e0c-40fb-8eda-4eeeb5258048.png)

**Comment by devblackhunter** [comment]
LAZY_IMPORTER_CASE_INSENSITIVE very helpful guys 🙂

**Comment by devblackhunter** [comment]
My fix:

1. Preload all libraries
2. Then LI_FN().in(LI_MODULE().get())

**Comment by JustasMasiulis** [comment]
> Preload all libraries

Yeah, that's what you need to do when they aren't auto loaded because your exe doesn't "import" anything from them anymore.

> Then LI_FN().in(LI_MODULE().get())

Sounds like you might be using something forwarded.

**Comment by devblackhunter** [comment]
![image](https://user-images.githubusercontent.com/45397007/213886465-d4b5cb1d-3047-4fee-b21e-6809693200e1.png)
I can't understand why, but after using LI_FN, writing to a file via ostream stops working. (without works fine)

**Comment by devblackhunter** [comment]
![image](https://user-images.githubusercontent.com/45397007/213887477-22dc04a7-8a98-4735-aecf-60e4c5c9176e.png)
It still crash

**Comment by devblackhunter** [comment]
I think there is a problem with Co_* functions (from Ole32.dll for example)

**Comment by JustasMasiulis** [comment]
Apiset resolution isn't supported. Use `combase.dll` instead of `ole32.dll`.
