### ISSUE TITLE
LI_FIND Exception when used in constructor()

### ISSUE THREAD

**Issue by Mecanik** [JustasMasiulis/lazy_importer#5]
Hi, I tried to used LI_FIND in a class constructor but it exits instantly.

Is there anything we could regarding this ?

Thanks

**Comment by JustasMasiulis** [comment]
I do not think that this is related to constructor itself as there is practically no difference wherever it's used. Might be a bug somewhere the code.

**Comment by Mecanik** [comment]
Well the function I tried with is InitialiseCriticalSection(), would take many a difference ?

**Comment by JustasMasiulis** [comment]
Yeah that's a forwarded export. You can use the Rtl functions to work with critical section without forwarded exports. (RtlInitializeCriticalSection, etc).
