### ISSUE TITLE
Can't compile on Debian x64 gcc

### ISSUE THREAD

**Issue by DenisM3lo** [JustasMasiulis/lazy_importer#50]
The compiler complains about missing intrin.h, needed for the __readgsqword() calls.
intrin.h is available for Windows with msvc and mingw.

If more info is needed I wold be happy to help.

**Comment by JustasMasiulis** [comment]
I would suggest compiling with clang instead.

If this is a really pressing issue for you I could fix it, but this seems like a rather niche issue...

**Comment by DenisM3lo** [comment]
Hi!
I didn't tried to compile with clang because I'm trying to embed the header in a hard cross platform structured project. But if you willing to explain maybe I can fix it, or even do a pull request.

**Comment by JustasMasiulis** [comment]
Sorry for the delay. Your issue should be fixed.

**Comment by DenisM3lo** [comment]
Hi, thanks for the fix. Unfortunately, I hadn't time to test it yet.
