### ISSUE TITLE
Unhandled exception at (netapi32.dll) 

### ISSUE THREAD

**Issue by romanholidaypancakes** [JustasMasiulis/lazy_importer#52]
win10 32bit exe
```
LPWSTR name = NULL;
NETSETUP_JOIN_STATUS    net;
LI_FN(NetGetJoinInformation)((LPCWSTR)NULL, &name, &net);
```

**Comment by JustasMasiulis** [comment]
1. Is the exception an attempt to call null pointer.
2. Is the dll that contains that function actually loaded.
3. did you enable forwarded import resolution & case insensitive comparison.

**Comment by JustasMasiulis** [comment]
> I'm using lazy_importer's default settings without changing any code

So... Did you try enabling forwarded import resolution and case insensitive comparison?

**Comment by JustasMasiulis** [comment]
Most likely an api-set export. Won't be fixed unless there is large demand for this.
