### ISSUE TITLE
Can't find function GetProcAddressForCaller

### ISSUE THREAD

**Issue by rxznve** [JustasMasiulis/lazy_importer#56]
```
#include <Windows.h>
#include <iostream>

#define LAZY_IMPORTER_CASE_INSENSITIVE
#include "lazy_importer/include/lazy_importer.hpp"

int main()
{
	const HMODULE hModule = LI_MODULE("kernelbase.dll").safe<HMODULE>();

	if (!hModule)
		return FALSE;

	std::wcout << GetProcAddress(hModule, "GetProcAddressForCaller") << std::endl;
	std::wcout << LI_FN("GetProcAddressForCaller").in_safe(hModule) << std::endl;

	system("pause");
	return 0;
}
```

Result:
**00007FFEB4BB1830** (GetProcAddress(hModule, "GetProcAddressForCaller"))
**0000000000000000** (LI_FN("GetProcAddressForCaller").in_safe(hModule))

Why?

**Comment by rxznve** [comment]
By the way, if you enter
`const HMODULE hModule = LI_MODULE("KernelBase.dll").safe<HMODULE>();`
Without use
`#define LAZY_IMPORTER_CASE_INSENSITIVE`
lazy_importer will somehow loop and the application will start to load the processor very much

**Comment by JustasMasiulis** [comment]
`std::wcout << LI_FN("GetProcAddressForCaller").in_safe(hModule) << std::endl;`

Is not valid usage of LI_FN - the macro does not accept strings, it expects the verbatim name of the thing you want.
