### ISSUE TITLE
[Question] Import libriries not loaded in the memory space

### ISSUE THREAD

**Issue by Guila767** [JustasMasiulis/lazy_importer#57]
I have a question about the behavior of this library. While testing it, I observed that attempting to 'import' functions from modules not loaded into the current memory space results in failure. This behavior seems aligned with the library's apparent reliance on enumerating modules within the PEB's LDR.

Does this library have the capability to implicitly or explicitly load modules into the process memory space, or if manual usage of LoadLibrary required for this purpose?

**Comment by Guila767** [comment]
I figured it out. I looked more deeply at the source code and some closed issues.

**Comment by JustasMasiulis** [comment]
Sorry for late reply.

> Does this library have the capability to implicitly or explicitly load modules into the process memory space, or if manual usage of LoadLibrary required for this purpose?

This library does not load modules. You need to ensure that yourself.
