### ISSUE TITLE
How to call overridden functions?

### ISSUE THREAD

**Issue by 1337331** [JustasMasiulis/lazy_importer#58]
I have tried many things(example is memchr):
`void* (*memchrPtr)(void*, int, size_t) = memchr;`
`const char* p = (const char*)LI_FN(memchrPtr)((void*)str, (int)c, str_end - str);`
> 'type cast': cannot convert from 'void' to 'const char *'

it return void (this has nothing to do with void*, all types return void)

`const char* p = (const char*)LI_FN_DEF(void* (*)(void*, int, size_t)))((void*)str, (int)c, str_end - str);`
this should work, but I can't find document about it
and what if there are functions of the same type in same module

anyway thanks to contributors
LI works well in most cases

**Comment by JustasMasiulis** [comment]
I'm sorry, but what exactly are you trying to do?

`LI_FN(memchrPtr)` is going to look for an export named "memchrPtr", same with the `LI_FN_DEF(void* (*)(void*, int, size_t)))` looking for the literal representation of the typedef instead of the name.

**Comment by 1337331** [comment]
@JustasMasiulis 
> I'm sorry, but what exactly are you trying to do?
> 
> `LI_FN(memchrPtr)` is going to look for an export named "memchrPtr", same with the `LI_FN_DEF(void* (*)(void*, int, size_t)))` looking for the literal representation of the typedef instead of the name.

I want to import memchr using lazy import
memchr has two overloads:
```
void* memchr(void* _Pv, int _C, size_t _N);
void* memchr(const void* _Buf, int _Val, size_t _MaxCount);
```
![8tAYmKglT4](https://github.com/JustasMasiulis/lazy_importer/assets/20391409/f8dca8ac-2fbd-4270-8ea2-f603e5330c1a)

**Comment by JustasMasiulis** [comment]
I would imagine one of the overloads is an inline definition for C++ only. I don't really have a good solution for this.

**Comment by 1337331** [comment]
> I would imagine one of the overloads is an inline definition for C++ only. I don't really have a good solution for this.

Can you give a correct example of LI_FN_DEF?
Or maybe specify a function name string and customize hash and use `in<T = F, A>(A module_address) -> T` to retrieve export in specified module?

**Comment by JustasMasiulis** [comment]
> > I would imagine one of the overloads is an inline definition for C++ only. I don't really have a good solution for this.
> 
> Can you give a correct example of LI_FN_DEF? 

```cpp
using memchr = void(*)(void*, int, size_t);
LI_FN_DEF(memchr)(...); // the typedef name needs to be the name of export.
```

Or maybe specify a function name string and customize hash and use `in<T = F, A>(A module_address) -> T` to retrieve export in specified module?

```cpp
#define LI_FN(name) ::li::detail::lazy_function<LAZY_IMPORTER_KHASH(#name), decltype(&name)>()
#define LI_FN_DEF(name) ::li::detail::lazy_function<LAZY_IMPORTER_KHASH(#name), name>()
```

`lazy_function` is the thing under the macro, so you can use it however you want - it's just that there isn't some "nice" way to do what you want besides using it directly.

```cpp
using the_memchr_I_care_about = void(*)(void*, int, size_t);
::li::detail::lazy_function<LAZY_IMPORTER_KHASH("the name of memchr export"), the_memchr_I_care_about >()

// you can create your own macro
#define MY_OVERLOADED_IMPORT_THING(function, type) ::li::detail::lazy_function<LAZY_IMPORTER_KHASH(#function), type>()
MY_OVERLOADED_IMPORT_THING(memchr, void(*)(void*, int, size_t))(...)
````

**Comment by 1337331** [comment]
> > > I would imagine one of the overloads is an inline definition for C++ only. I don't really have a good solution for this.
> > 
> > 
> > Can you give a correct example of LI_FN_DEF?
> 
> ```c++
> using memchr = void(*)(void*, int, size_t);
> LI_FN_DEF(memchr)(...)
> ```
> 
> Or maybe specify a function name string and customize hash and use `in<T = F, A>(A module_address) -> T` to retrieve export in specified module?
> 
> ```c++
> #define LI_FN(name) ::li::detail::lazy_function<LAZY_IMPORTER_KHASH(#name), decltype(&name)>()
> #define LI_FN_DEF(name) ::li::detail::lazy_function<LAZY_IMPORTER_KHASH(#name), name>()
> ```
> 
> `lazy_function` is the thing under the macro, so you can use it however you want - it's just that there isn't some "nice" way to do what you want besides using it directly.
> 
> ```c++
> using the_memchr_I_care_about = void(*)(void*, int, size_t);
> ::li::detail::lazy_function<LAZY_IMPORTER_KHASH("the name of memchr export"), the_memchr_I_care_about >()
> ```

Have not had time to test it yet, but it looks good.
Thank you very much for your prompt reply and enthusiastic help!
