### ISSUE TITLE
LAZY_IMPORTER_FORCEINLINE Exception 

### ISSUE THREAD

**Issue by Mecanik** [JustasMasiulis/lazy_importer#6]
Calling LI_FIND(OpenProcessToken) will throw exception at:

```
LAZY_IMPORTER_FORCEINLINE const win::LDR_DATA_TABLE_ENTRY_T* ldr_data_entry() noexcept
    {
        return reinterpret_cast<const win::LDR_DATA_TABLE_ENTRY_T*>(
            ldr()->InLoadOrderModuleList.Flink);
    }
```

Any solution for this ? Function in Advapi32.dll

**Comment by JustasMasiulis** [comment]
That is strange. OpenProcessToken is a forwarded export IIRC so enabling that might possibly help.

**Comment by kateon11** [comment]
Most likely because the module it tries to find does not exist, starting with windows 7+, OpenProcessToken is a forwarded export to "api-ms-win-core-processthreads-l1-1-0", which resolves to kernel32.dll, and LI does not handle api set resolutions for virtual dlls.

**Comment by Mecanik** [comment]
@kateon11 You are correct... thank you!

For now I just ignore certain functions...

**Comment by JustasMasiulis** [comment]
Forwarded exports are supported, but not enabled by default as there is some overhead.

Try defining LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS and LAZY_IMPORTER_CASE_INSENSITIVE.

That should solve your problems. Alternatively the native API is essentially 1:1 on the usage side IIRC.
