### ISSUE TITLE
Please ask us if you have any questions about how to use it

### ISSUE THREAD

**Issue by MyWare123** [JustasMasiulis/lazy_importer#60]
```
#include <windows.h>
#include "lazy_importer.hpp"
int main()
{
    LI_MODULE("user32.dll");
    LI_FN(MessageBoxA)(HWND(0), "test", "test", NULL);
    return 0;
}
```
1.My program itself is not loading the user32 module, I use the LI_MODULE macro can't be loaded?
2.Use the example you wrote "LI_FN(VirtualProtect).in(LI_MODULE("kernel32.dll").cached());" Now I don't know how to use the export function correctly without loading the module, can you help or write a more detailed case.
![image](https://github.com/JustasMasiulis/lazy_importer/assets/63500731/b4a04e65-403d-4767-ba8b-289d4f88f166)

**Comment by MyWare123** [comment]
```
#include <windows.h>
#include "lazy_importer.hpp"
int main()
{
    LI_FN(LoadLibraryA)("user32.dll");
    LI_FN(MessageBoxA)(HWND(0), "test", "test", NULL);
    return 0;
}
```
But I didn't understand "LI_FN(MessageBoxA).in(LI_MODULE("user32.dll").cached());" Why can't that?

**Comment by JustasMasiulis** [comment]
> But I didn't understand "LI_FN(MessageBoxA).in(LI_MODULE("user32.dll").cached());" Why can't that?

Try adding `#define LAZY_IMPORTER_RESOLVE_FORWARDED_EXPORTS` and `#define LAZY_IMPORTER_CASE_INSENSITIVE` before your `lazy_import.hpp` include.
