### ISSUE TITLE
Add safe versions of import functions.

### ISSUE THREAD

**Issue by JustasMasiulis** [JustasMasiulis/lazy_importer#8]
Current import functions crash the process on failure to find the requested data.

**Comment by Mecanik** [comment]
We could hard code a huge list, however it’s a daunting task...

How about throwing a safe exception ?

**Comment by JustasMasiulis** [comment]
I was thinking about just returning 0. It's just an issue to remind myself to implement this functionality.

**Comment by JustasMasiulis** [comment]
Solved in the newest version of library. Don't rush to pull yet though as it is API breaking.
